# Generated by Django 6.0.3 on 2026-03-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
